// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ8Sl7z6iIe3PVmB9-IysBHwCQ6siE4xw',
    appId: '1:474804835371:web:d453afc7f03f00f17bc66e',
    messagingSenderId: '474804835371',
    projectId: 'learning-platform-2cd28',
    authDomain: 'learning-platform-2cd28.firebaseapp.com',
    storageBucket: 'learning-platform-2cd28.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBVQ83xe3qSlYOvskQ5RobGR-Uaa_B5mw',
    appId: '1:474804835371:android:cca3b4744b55accd7bc66e',
    messagingSenderId: '474804835371',
    projectId: 'learning-platform-2cd28',
    storageBucket: 'learning-platform-2cd28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Z7BoAylaK2W5wzch78MMpzP3uxCbFeA',
    appId: '1:474804835371:ios:381ed0b75f5d19987bc66e',
    messagingSenderId: '474804835371',
    projectId: 'learning-platform-2cd28',
    storageBucket: 'learning-platform-2cd28.appspot.com',
    iosBundleId: 'com.example.learningPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Z7BoAylaK2W5wzch78MMpzP3uxCbFeA',
    appId: '1:474804835371:ios:381ed0b75f5d19987bc66e',
    messagingSenderId: '474804835371',
    projectId: 'learning-platform-2cd28',
    storageBucket: 'learning-platform-2cd28.appspot.com',
    iosBundleId: 'com.example.learningPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ8Sl7z6iIe3PVmB9-IysBHwCQ6siE4xw',
    appId: '1:474804835371:web:669f6a9e1586a7f07bc66e',
    messagingSenderId: '474804835371',
    projectId: 'learning-platform-2cd28',
    authDomain: 'learning-platform-2cd28.firebaseapp.com',
    storageBucket: 'learning-platform-2cd28.appspot.com',
  );

}